var selectedText="",focusedInput,startIndex,shouldGoBackHide=0,notClicked=!0,file,colourTemplate='{\n   "Lecture": "#b0c4de",\n   "Practical": "#b0c4de",\n   "Tutorial": "#b0c4de",\n   "Remark": "#81c784",\n   "E-Learning": "#81c784",\n   "In Course Assessment": "#FA8072"\n}',selectOptions="{'Lecture','Practical','Tutorial','Remark','E-Learning','In Course Assessment'}";
$(function(){$(".carousel-control-prev").css("display","none");clearImportTextarea();$(window.document).on("focusout","#linkInput",checkAndDisplayAlert);if($(".inputDiv").addEventListener)$(".inputDiv").addEventListener("contextmenu",function(a){focusedInput=$(":focus");if("undefined"!=typeof window.getSelection){var d=window.getSelection();d.rangeCount&&(startIndex=d.focusOffset)}else"undefined"!=typeof document.selection&&"Text"==window.document.selection.type&&(startIndex=sel.focusOffset);window.getSelection?
selectedText=window.getSelection().toString():window.document.selection&&"Control"!=window.document.selection.type&&(selectedText=window.document.selection.createRange().text);selectedText&&($("#rightClickMenu").css("display","block"),$("#rightClickMenu").offset({left:a.pageX,top:a.pageY}),a.preventDefault())},!1);else $("body").on("contextmenu",".inputDiv",function(a){focusedInput=$(":focus");if("undefined"!=typeof window.getSelection){var d=window.getSelection();d.rangeCount&&(startIndex=d.focusOffset)}else"undefined"!=
typeof document.selection&&"Text"==document.selection.type&&(startIndex=sel.focusOffset);window.getSelection?selectedText=window.getSelection().toString():document.selection&&"Control"!=document.selection.type&&(selectedText=document.selection.createRange().text);selectedText&&($("#rightClickMenu").css("display","block"),$("#rightClickMenu").offset({left:a.pageX,top:a.pageY}),window.event.returnValue=!1)});$(document).bind("click",function(a){$("#rightClickMenu").css("display","none")});$(document).on("mouseover",
".contentDivDivDraggableDiv",function(){$(this).stop(!0,!0);$(this).animate({opacity:1,queue:!1},300)});$(document).on("mouseout",".contentDivDivDraggableDiv",function(){$(this).animate({opacity:0},300)});$(document).on("change","#excelSelectInput",function(){$(this).hasClass("is-invalid")&&($(this).removeClass("is-invalid"),$(this).addClass("is-valid"))});$(document).on("change",".remapExcelSelectInput",function(){$(this).hasClass("is-invalid")&&($(this).removeClass("is-invalid"),$(this).addClass("is-valid"))});
contentEditableBr();document.body.style.cursor="auto"});function goPage2(){$("#carousel").carousel("next");$("#carousel").carousel("pause");$(".carousel-control-prev").css("display","flex");shouldGoBackHide++}function goPage3(a){$("#carousel").carousel("next");$("#carousel").carousel("pause");$(".carousel-control-prev").css("display","flex");shouldGoBackHide++;$("#importPage3Preview").empty();$("#importPage3Preview").append(a)}
function goBack(){closeAlert();$("#carousel").carousel("prev");$("#carousel").carousel("pause");shouldGoBackHide--;0>=shouldGoBackHide&&$(".carousel-control-prev").css("display","none")}function createNew(){$("#startupDiv").fadeOut();$("#masterDiv").css("overflow","auto");$("#masterDiv").css("height","unset");$("#page1").empty();recreatePage1()}function closeAlert(){$(".alert").alert("close")}
function checkTextIsCorrect(){closeAlert();var a=document.createElement("div");a.className="alert alert-danger fade show";a.id="page2Error";a.setAttribute("role","alert");var d=document.createElement("p"),c=document.createElement("div"),b=document.createElement("button");b.className="close";b.setAttribute("type","button");b.setAttribute("data-dismiss","alert");b.setAttribute("aria-label","Close");var e=document.createElement("span");b.setAttribute("aria-hidden","true");b.innerHTML="&times;";b.appendChild(e);
c.appendChild(b);a.appendChild(d);a.appendChild(c);(c=$("#importTextarea").val().trim())?(b=$(document.createElement("div")),b.html(c),(c=b.find("#lessonPlanTemplate").html())?(c=c.trim(),0<c.length?(d=document.createElement("div"),d.id="lessonPlanTemplate",$(d).html(c),goPage3(d)):(d.appendChild(document.createTextNode("'id=#lessonPlanTemplate' div is empty. Make sure you entered/uploaded correctly")),$("#startupDivPage2 > div").prepend(a),$("#page2Error").slideDown(function(){a.style.display="flex"}))):
(d.appendChild(document.createTextNode("'id=#lessonPlanTemplate' div missing. Make sure you entered/uploaded correctly")),$("#startupDivPage2 > div").prepend(a),$("#page2Error").slideDown(function(){a.style.display="flex"}))):(d.appendChild(document.createTextNode("Make sure you entered/uploaded something")),$("#startupDivPage2 > div").prepend(a),$("#page2Error").slideDown(function(){a.style.display="flex"}))}
function fileMatchesLayout(a){closeAlert();var d=document.createElement("div");d.className="alert alert-danger fade show";d.id="page2Error";d.setAttribute("role","alert");var c=document.createElement("p"),b=document.createElement("div"),e=document.createElement("button");e.className="close";e.setAttribute("type","button");e.setAttribute("data-dismiss","alert");e.setAttribute("aria-label","Close");var k=document.createElement("span");e.setAttribute("aria-hidden","true");e.innerHTML="&times;";e.appendChild(k);
b.appendChild(e);d.appendChild(c);d.appendChild(b);if(a=a.trim())if(b=$(document.createElement("div")),b.html(a),a=b.find("#lessonPlanTemplate").html()){a=a.trim();if(0<a.length)return!0;c.appendChild(document.createTextNode("'id=#lessonPlanTemplate' div is empty. Make sure you entered/uploaded correctly"))}else c.appendChild(document.createTextNode("'id=#lessonPlanTemplate' div missing. Make sure you entered/uploaded correctly"));else c.appendChild(document.createTextNode("Make sure you entered/uploaded something"));
$("#startupDivPage2 > div").prepend(d);$("#page2Error").slideDown(function(){d.style.display="flex"});return!1}function hideStartupDiv(){$("#page2").empty();$("#page2").html($("#importPage3Preview").html());$("#importPage3Preview").empty();createNew()}
function allowDrop(a){window.File&&window.FileReader&&window.FileList&&window.Blob?($("#importTextarea").css("border","5px dashed grey"),$("#importTextarea").css("border-radius","20px"),a.preventDefault()):alert("Browser doesn't support drag and drop")}function removeDragCSS(){$("#importTextarea").css("border","");$("#importTextarea").css("border-radius","")}
function drop(a){a.preventDefault();removeDragCSS();$(".progress-bar").css("width","0%");$(".progress-bar")[0].classList.add("progress-bar-animated");$("#remappingDiv").collapse("hide");$("#remapIcon")[0].classList.add("fa-plus-square");$("#remapIcon")[0].classList.remove("fa-minus-square");a=a.dataTransfer?a.dataTransfer.files:a.target.files;if(!a[0])return!1;file=a[0];var d=new FileReader;file.type.match("text/plain")||file.type.match("text/html")?(d.onload=function(){var a=d.result;fileMatchesLayout(a)&&
($("#uploadedFileName").html(file.name),$("#importTextarea").val(a))},d.onprogress=function(a){a.lengthComputable&&(a=parseInt(a.loaded/a.total*100,10),$(".progress-bar").css("width",a+"%"),console.log(a))},d.onloadend=function(){$(".progress-bar")[0].classList.remove("progress-bar-animated")}):file.type.match("application/vnd.ms-excel")||file.type.match("application/vnd.openxmlformats-officedocument.spreadsheetml.sheet")?(showColumn(file),$("#excelBoxDiv").modal("show")):alert("Only .html, .txt & .xls(x) is the accepted file format");
d.readAsText(file)}
function showColumn(a){var d=new FileReader;d.onload=function(a){var b="";a=new Uint8Array(a.target.result);for(var d=a.byteLength,c=0;c<d;c++)b+=String.fromCharCode(a[c]);b=XLSX.read(b,{type:"binary",cellDates:!0,cellStyles:!0});$("#excelSelectInput").empty();$("#excelSelectInput2").empty();a=$("<option disabled selected>Please select your primary column</option>");$("#excelSelectInput").append(a);a=$("<option selected>Please select your secondary column</option>");$("#excelSelectInput2").append(a);b=
b.Sheets[b.SheetNames[0]];a=XLSX.utils.decode_range(b["!ref"]);$("#remappingDiv > .card-body").empty();for(d=a.s.c;d<=a.e.c;d++)if(c=XLSX.utils.encode_cell({c:d,r:0}),b[c]){var l=String(b[c].v);c=document.createElement("option");c.appendChild(document.createTextNode(l));c.value=d;var h=document.createElement("option");h.appendChild(document.createTextNode(l));h.value=d;$("#excelSelectInput").append(c);$("#excelSelectInput2").append(h);c=document.createElement("div");c.className="form-group";h=document.createElement("p");
h.appendChild(document.createTextNode("Table Header: "));h.className="remapColumnHeader";var z=document.createElement("p");z.appendChild(document.createTextNode(l));l=document.createElement("p");l.appendChild(document.createTextNode("Map to: "));l.className="remapColumnHeader";var m=document.createElement("select");m.className="custom-select remapExcelSelectInput";m.style.marginBottom="8px";var B=document.createElement("option");B.appendChild(document.createTextNode("Select an option"));B.selected=
!0;var p=document.createElement("option");p.appendChild(document.createTextNode("Lecture"));p.setAttribute("value","0");var f=document.createElement("option");f.appendChild(document.createTextNode("Practical"));f.setAttribute("value","1");var n=document.createElement("option");n.appendChild(document.createTextNode("Tutorial"));n.setAttribute("value","2");var q=document.createElement("option");q.appendChild(document.createTextNode("Remark"));q.setAttribute("value","3");var g=document.createElement("option");
g.appendChild(document.createTextNode("E-Learning"));g.setAttribute("value","4");var r=document.createElement("option");r.appendChild(document.createTextNode("In Course Assessment"));r.setAttribute("value","5");m.appendChild(B);m.appendChild(p);m.appendChild(f);m.appendChild(n);m.appendChild(q);m.appendChild(g);m.appendChild(r);c.appendChild(h);c.appendChild(z);c.appendChild(l);c.appendChild(m);$("#remappingDiv > .card-body").append(c)}};d.readAsArrayBuffer(a)}
function excelMoveToPage(a){switch(a){case 1:$("#excelPage1").fadeIn();$("#excelPage2").fadeOut();break;case 2:$("#excelSelectInput").val()&&0<=$("#excelSelectInput").val()?($("#excelPage3")[0].style.left="5%",$("#excelPage3")[0].style.top="10%",$("#excelPage3").css("position","absolute"),$("#excelPage1").fadeOut(),$("#excelPage2").fadeIn(),$("#excelPage3").fadeOut(),$(".modal-footer > button:nth-child(2)").css("display","none")):$("#excelSelectInput").addClass("is-invalid");$("#excelPage3 > .excelPopupButtonDiv > button").css("position",
"block");break;case 3:$("#excelPage2").fadeOut();$("#excelPage3").fadeIn(function(){$("#excelPage3")[0].style.left=0;$("#excelPage3")[0].style.top=0;$("#excelPage3").css("position","relative")});$(".modal-footer > button:nth-child(2)").css("display","block");break;default:alert("What? How is this possible... Stop it")}}
function startProcessingExcel(){var a;if($("#excelSelectInput").val()&&0<=$("#excelSelectInput").val()){var d=document.getElementById("customControlAutosizing").checked,c=document.createElement("div");c.id="lessonPlanTemplate";var b=document.createElement("p");b.appendChild(document.createTextNode("Instructors Details"));var e=document.createElement("div");b.className="bold underline";e.id="instructorsDetails";c.append(b);c.append(e);var k=$("#excelSelectInput").val(),l=$("#excelSelectInput2").val();
0<=k&&($("#uploadedFileName").html(file.name),b=new FileReader,b.onload=function(b){var e="";b=new Uint8Array(b.target.result);for(var m=b.byteLength,h=0;h<m;h++)e+=String.fromCharCode(b[h]);e=XLSX.read(e,{type:"binary",cellDates:!0,cellStyles:!0});e=e.Sheets[e.SheetNames[0]];b=a=XLSX.utils.decode_range(e["!ref"]);m={lecture:[],practical:[],tutorial:[],remark:[],eLearning:[],iCA:[]};m=getRemapFromInput(m,k,l);h=[];for(var p=b.s.c;p<=b.e.c;p++){var f=!1;for(keyValue in m)if(m.hasOwnProperty(keyValue))for(i=
0;i<m[keyValue].length;i++)if(parseInt(m[keyValue][i])===p){f=!0;break}f||(f=XLSX.utils.encode_cell({c:p,r:0}),e[f]&&(f=String(e[f].v).toLowerCase(),-1!==f.indexOf("lecture")?m.lecture.push(p):-1!==f.indexOf("practical")?m.practical.push(p):-1!==f.indexOf("tutorial")?m.tutorial.push(p):-1!==f.indexOf("remark")?m.remark.push(p):-1!==f.indexOf("e-learning")||-1!==f.indexOf("elearning")?m.eLearning.push(p):-1!==f.indexOf("ica")||-1!==f.indexOf("in course assessment")?m.iCA.push(p):p!==parseInt(k)&&p!==
parseInt(l)&&h.push(p)))}if(0<h.length){p="Some columns could not be mapped automatically. Do you want to continue without mapping the Column(s): ";f=!0;for(var n=0;n<h.length;n++){var q=XLSX.utils.encode_cell({c:h[n],r:0});e[q]&&(q=String(e[q].v),$("#remappingDiv > .card-body").children().eq(h[n]).find("select").addClass("is-invalid"),f?(p+=q,f=!1):p=n===h.length-1?p+(" & "+q+"?"):p+(", "+q))}if(!confirm(p))return!1}for(h=b.s.r+1;h<=b.e.r;h++)if(p=XLSX.utils.encode_cell({c:k,r:h}),e[p]){var g=e[p],
r=String(g.v);p=document.createElement("div");f=document.createElement("div");n=document.createElement("p");q=document.createElement("p");p.className="lesson";f.className="lessonHeader";n.className="bold";q.className="em";g.l?isNaN(g.v)?$(n).html("<a href='"+g.l.Target+"' target='_blank'>"+g.v+"</a>"):$(n).html("<a href='"+g.l.Target+"' target='_blank'>Week "+g.v+"</a>"):isNaN(g.v)?$(n).html(r):$(n).html("Week "+r);l&&0<=l&&(g=checkIfMerged(e,l,h),g=g.found?XLSX.utils.encode_cell({c:g.sC,r:g.sR}):
XLSX.utils.encode_cell({c:l,r:h}),e[g]&&(g=e[g],r=String(g.v),g.l?isNaN(g.v)?$(q).html("<a href='"+g.l.Target+"' target='_blank'>"+g.v+"</a>"):$(q).html("<a href='"+g.l.Target+"' target='_blank'>Week "+g.v+"</a>"):isNaN(g.v)?$(q).html(r):$(q).html("Week "+r)));f.appendChild(n);f.appendChild(q);p.appendChild(f);f=checkIfMerged(e,k,h);if("row"===f.direction)for(f=f.eR-f.sR,n=b.s.c;n<=b.e.c;n++){if(q=null,n!=k&&n!=l){for(g=h;g<=h+f;g++)if(!(g>h&&"row"===checkIfMerged(e,n,h).direction)){r=checkIfMerged(e,
n,g);var t="column"===r.direction||"both"===r.direction?XLSX.utils.encode_cell({c:r.sC,r:r.sR}):XLSX.utils.encode_cell({c:n,r:g});if(e[t]){var v=getHeader(m,n);r=v.header;var u=v.lecPrac,x=document.createElement("div"),y=document.createElement("p");v=document.createElement("ul");x.className="lessonPlanContent";y.className="lessonPlanContentP";var w=e[t];t=String(w.v).trim().split("\n");var A="";if(w.l){t=w.v.trim().split("\n");for(var C=0;C<t.length;C++)A+="<li><a href='"+w.l.Target+"' target='_blank'>"+
t[C]+"</a></li>"}else for(w=0;w<t.length;w++)A+="<li>"+t[w]+"</li>";$(v).html(A);x.appendChild(y);x.appendChild(v);r.appendChild(u);r.appendChild(x);p.appendChild(r);d&&(q?g>h&&("row"===checkIfMerged(e,n,h).direction||"both"===checkIfMerged(e,n,h).direction)||(u=q.find(".lessonPlanContent > ul"),v=u.html()+v.innerHTML,$(u).html(v),$(r).remove()):q=$(r))}}c.appendChild(p)}}else{for(f=b.s.c;f<=b.e.c;f++)if(f!=k&&f!=l&&(n=checkIfMerged(e,f,h),u="column"===n.direction||"both"===n.direction||"row"===n.direction?
XLSX.utils.encode_cell({c:n.sC,r:n.sR}):XLSX.utils.encode_cell({c:f,r:h}),e[u])){q=getHeader(m,f);n=q.header;q=q.lecPrac;g=document.createElement("div");r=document.createElement("p");v=document.createElement("ul");g.className="lessonPlanContent";r.className="lessonPlanContentP";y=e[u];u=String(y.v).trim().split("\n");x="";if(y.l)for(u=y.v.trim().split("\n"),t=0;t<u.length;t++)x+="<li><a href='"+y.l.Target+"' target='_blank'>"+u[t]+"</a></li>";else for(y=0;y<u.length;y++)x+="<li>"+u[y]+"</li>";$(v).html(x);
g.appendChild(r);g.appendChild(v);n.appendChild(q);n.appendChild(g);p.appendChild(n)}c.appendChild(p)}}$("#importTextarea").val(c.outerHTML);$("#excelBoxDiv").modal("hide");$("#excelSelectInput").removeClass("is-valid");excelMoveToPage(2);excelMoveToPage(1)},b.onprogress=function(a){a.lengthComputable&&(a=parseInt(a.loaded/a.total*100,10),$(".progress-bar").css("width",a+"%"))},b.onloadend=function(){$(".progress-bar")[0].classList.remove("progress-bar-animated")},b.readAsArrayBuffer(file))}else $("#excelSelectInput").addClass("is-invalid")}
function getHeader(a,d){var c=document.createElement("div"),b=document.createElement("div"),e=document.createElement("p");b.appendChild(e);c.className="lecPracHeader";b.className="lecPracDiv";e.className="bold";var k=checkIfColumnsHeader(a,d);k?($(e).html(k),e=JSON.parse(colourTemplate),e[k]&&(b.style.background=e[k])):($(e).html("Lecture"),k=JSON.parse(colourTemplate),k.Lecture&&(b.style.background=k.Lecture));return{header:c,lecPrac:b}}
function checkIfColumnsHeader(a,d){var c=null,b;for(b in a)if(a.hasOwnProperty(b))for(i=0;i<a[b].length;i++)if(parseInt(a[b][i])===d)if("lecture"===b){c="Lecture";break}else if("practical"===b){c="Practical";break}else if("tutorial"===b){c="Tutorial";break}else if("remark"===b){c="Remark";break}else if("eLearning"===b){c="E-Learning";break}else if("iCA"===b){c="In Course Assessment";break}return c}
function getRemapFromInput(a,d,c){$("#remappingDiv > .card-body").children().each(function(b){if(b===d||b===c)return!1;switch(parseInt($(this).find("select").val())){case 0:a.lecture.push(b);break;case 1:a.practical.push(b);break;case 2:a.tutorial.push(b);break;case 3:a.remark.push(b);break;case 4:a.eLearning.push(b);break;case 5:a.iCA.push(b)}});return a}
function disableRemap(){$("#remappingDiv > .card-body").children().each(function(){var a=$(this).find("select");a[0].hasAttribute("disabled")&&a.removeAttr("disabled")});if($("#excelSelectInput").val()){var a=$("#remappingDiv > .card-body").children().eq($("#excelSelectInput").val()).find("select");a.attr("disabled","disabled");a[0].selectedIndex="0"}0!==$("#excelSelectInput2")[0].selectedIndex&&(a=$("#remappingDiv > .card-body").children().eq($("#excelSelectInput2").val()).find("select"),a.attr("disabled",
"disabled"),a[0].selectedIndex="0")}function changeRemapIcon(){$("#remapIcon").hasClass("fa-plus-square")?($("#remapIcon")[0].classList.add("fa-minus-square"),$("#remapIcon")[0].classList.remove("fa-plus-square")):($("#remapIcon")[0].classList.add("fa-plus-square"),$("#remapIcon")[0].classList.remove("fa-minus-square"))}
function checkIfMerged(a,d,c){if(a=a["!merges"]){a=Object.values(a);for(var b=0;b<a.length;b++){var e=a[b].s.c,k=a[b].e.c,l=a[b].s.r,h=a[b].e.r;if(d>=e&&d<=k&&c>=l&&c<=h){if(k>e)return h>l?{found:!0,sC:e,eC:k,sR:l,eR:h,direction:"both"}:{found:!0,sC:e,eC:k,sR:l,eR:h,direction:"column"};if(h>l)return{found:!0,sC:e,eC:k,sR:l,eR:h,direction:"row"}}}}return{found:!1,sC:null,eC:null,sR:null,eR:null,direction:"none"}}
function clearImportTextarea(){$("#inputGroupFile01").val(null);$("#uploadedFileName").html("Choose file");$("#importTextarea").val("");$(".progress-bar").css("width","0%")}
function makeSortable(){$(".mainSection").sortable({connectWith:".mainSection",items:".contentDivDiv",handle:".contentDivDivDraggableDiv",cancel:".inputDiv, textarea, input, button",update:function(){setActualValue()},axis:"y",cursor:"move",opacity:.5});$("#page1").sortable({items:".mainSection",cancel:":not('.draggableDiv')"})}function removeLessonContent(a){$(a).parent().fadeOut("swing",function(){$(a).parent().remove();recreatePage2()})}
function addLessonContent(a){var d=document.createElement("div"),c=document.createElement("div");c.className="contentDivDivDraggableDiv progress-bar-striped bg-success";c.style.opacity="0";var b=document.createElement("div");b.className="contentDivDivRight";var e=document.createElement("div"),k=document.createElement("p"),l=document.createElement("select"),h=document.createElement("input"),z=document.createElement("div"),m=document.createElement("div"),B=document.createElement("p"),p=document.createElement("div"),
f=document.createElement("input"),n=document.createElement("p"),q=document.createElement("div"),g=document.createElement("textarea"),r=document.createElement("button"),t=document.createElement("span");d.className="section contentDivDiv";e.className="leftDiv";l.className="inputDiv custom-select";h.className="form-control";z.className="flex rightDiv";m.className="page1Content";r.className="closeImg close";r.setAttribute("onclick","removeLessonContent(this)");r.setAttribute("type","button");r.setAttribute("aria-label",
"Close");t.setAttribute("aria-hidden","true");t.innerHTML="&times;";h.setAttribute("type","color");f.setAttribute("type","text");l.setAttribute("onchange","setActualColour(this)");h.setAttribute("onchange","setActualValue()");f.setAttribute("onkeyup","inputToDiv(this)");f.setAttribute("onkeydown","inputToDiv(this)");g.setAttribute("onkeyup","inputToDiv(this)");g.setAttribute("onkeydown","inputToDiv(this)");p.contentEditable="true";p.className="inputDiv contenteditableBr form-control";p.setAttribute("onkeyup",
"divToInput(this)");p.setAttribute("onkeydown","divToInput(this)");q.contentEditable="true";q.className="inputDiv form-control";q.setAttribute("onkeyup","divToInput(this)");q.setAttribute("onkeydown","divToInput(this)");$(q).html("<ul><li><br></li></ul>");$(q).keydown(function(a){if(8===a.keyCode&&"<ul><li><br></li></ul>"===$(this).html())return!1});var v=JSON.parse(colourTemplate);$(h).css("display","none");h.value=v.Lecture;$(f).css("display","none");$(g).css("display","none");$(g).text("<ul><li>>br></li></ul>");
v=document.createElement("option");v.appendChild(document.createTextNode("Lecture"));v.setAttribute("value","Lecture");var u=document.createElement("option");u.appendChild(document.createTextNode("Practical"));u.setAttribute("value","Practical");var x=document.createElement("option");x.appendChild(document.createTextNode("Tutorial"));x.setAttribute("value","Tutorial");var y=document.createElement("option");y.appendChild(document.createTextNode("Remark"));y.setAttribute("value","Remark");var w=document.createElement("option");
w.appendChild(document.createTextNode("E-Learning"));w.setAttribute("value","E-Learning");var A=document.createElement("option");A.appendChild(document.createTextNode("In Course Assessment"));A.setAttribute("value","In Course Assessment");l.appendChild(v);l.appendChild(u);l.appendChild(x);l.appendChild(y);l.appendChild(w);l.appendChild(A);k.appendChild(document.createTextNode("Lesson/ICA Type"));e.appendChild(k);e.appendChild(l);e.appendChild(h);B.appendChild(document.createTextNode("Title"));n.appendChild(document.createTextNode("Topics"));
m.appendChild(B);m.appendChild(p);m.appendChild(f);m.appendChild(n);m.appendChild(q);m.appendChild(g);z.appendChild(m);r.appendChild(t);b.appendChild(e);b.appendChild(z);d.appendChild(c);d.appendChild(b);d.appendChild(r);$(a).before(d);notClicked||($(".inputDiv").next().css("display","block"),$("textarea").css("display","block"));contentEditableBr();recreatePage2();makeSortable()}
function addLessonSection(a){var d=document.createElement("div"),c=document.createElement("div"),b=document.createElement("p"),e=document.createElement("div"),k=document.createElement("input"),l=document.createElement("p"),h=document.createElement("div"),z=document.createElement("input"),m=document.createElement("div"),B=document.createElement("div");B.className="contentDivDivDraggableDiv progress-bar-striped bg-success";B.style.opacity="0";var p=document.createElement("div");p.className="contentDivDivRight";
var f=document.createElement("div"),n=document.createElement("p"),q=document.createElement("select"),g=document.createElement("input"),r=document.createElement("div"),t=document.createElement("div"),v=document.createElement("p"),u=document.createElement("div"),x=document.createElement("input"),y=document.createElement("p"),w=document.createElement("div");document.createElement("ul");var A=document.createElement("textarea"),C=document.createElement("button"),F=document.createElement("span"),E=document.createElement("div"),
H=document.createElement("i"),I=document.createElement("p"),D=document.createElement("button"),G=document.createElement("span");d.className="mainSection section";c.className="lessonTitle";m.className="section contentDivDiv";f.className="leftDiv";q.className="inputDiv custom-select";g.className="form-control";r.className="flex rightDiv";t.className="page1Content";u.className="contenteditableBr form-control";C.className="closeImg close";C.setAttribute("onclick","removeLessonContent(this)");C.setAttribute("type",
"button");C.setAttribute("aria-label","Close");F.setAttribute("aria-hidden","true");F.innerHTML="&times;";I.appendChild(document.createTextNode("Add New Lesson/ICA"));H.className="fas fa-plus-circle";E.className="addLessonContent";E.setAttribute("onclick","addLessonContent(this)");D.className="closeImg close";D.setAttribute("onclick","removeLessonContent(this)");D.setAttribute("type","button");D.setAttribute("aria-label","Close");G.setAttribute("aria-hidden","true");G.innerHTML="&times;";k.setAttribute("type",
"text");k.className="lessonTitleInput form-control";z.setAttribute("type","text");z.className="lessonSubtitleInput form-control";g.setAttribute("type","color");x.setAttribute("type","text");k.setAttribute("onkeyup","inputToDiv(this)");k.setAttribute("onkeydown","inputToDiv(this)");z.setAttribute("onkeyup","inputToDiv(this)");z.setAttribute("onkeydown","inputToDiv(this)");q.setAttribute("onchange","setActualColour(this)");g.setAttribute("onchange","setActualValue()");x.setAttribute("onkeyup","inputToDiv(this)");
x.setAttribute("onkeydown","inputToDiv(this)");A.setAttribute("onkeyup","inputToDiv(this)");A.setAttribute("onkeydown","inputToDiv(this)");e.contentEditable="true";e.className="inputDiv contenteditableBr form-control";e.setAttribute("onkeyup","divToInput(this)");e.setAttribute("onkeydown","divToInput(this)");h.contentEditable="true";h.className="inputDiv contenteditableBr form-control";h.setAttribute("onkeyup","divToInput(this)");h.setAttribute("onkeydown","divToInput(this)");u.contentEditable="true";
u.className="inputDiv contenteditableBr form-control";u.setAttribute("onkeyup","divToInput(this)");u.setAttribute("onkeydown","divToInput(this)");w.contentEditable="true";w.className="inputDiv form-control";w.setAttribute("onkeyup","divToInput(this)");w.setAttribute("onkeydown","divToInput(this)");$(w).html("<ul><li><br></li></ul>");$(w).keydown(function(a){if(8===a.keyCode&&"<ul><li><br></li></ul>"===$(this).html())return!1});var J=JSON.parse(colourTemplate);$(k).css("display","none");$(z).css("display",
"none");$(g).css("display","none");g.value=J.Lecture;$(x).css("display","none");$(A).css("display","none");b.appendChild(document.createTextNode("Lesson Title"));l.appendChild(document.createTextNode("Subtitle Title"));c.appendChild(b);c.appendChild(e);c.appendChild(k);c.appendChild(l);c.appendChild(h);c.appendChild(z);b=document.createElement("option");b.appendChild(document.createTextNode("Lecture"));b.setAttribute("value","Lecture");e=document.createElement("option");e.appendChild(document.createTextNode("Practical"));
e.setAttribute("value","Practical");k=document.createElement("option");k.appendChild(document.createTextNode("Tutorial"));k.setAttribute("value","Tutorial");l=document.createElement("option");l.appendChild(document.createTextNode("Remark"));l.setAttribute("value","Remark");h=document.createElement("option");h.appendChild(document.createTextNode("E-Learning"));h.setAttribute("value","E-Learning");z=document.createElement("option");z.appendChild(document.createTextNode("In Course Assessment"));z.setAttribute("value",
"In Course Assessment");q.appendChild(b);q.appendChild(e);q.appendChild(k);q.appendChild(l);q.appendChild(h);q.appendChild(z);n.appendChild(document.createTextNode("Lesson/ICA Type"));f.appendChild(n);f.appendChild(q);f.appendChild(g);v.appendChild(document.createTextNode("Title"));y.appendChild(document.createTextNode("Topics"));t.appendChild(v);t.appendChild(u);t.appendChild(x);t.appendChild(y);t.appendChild(w);t.appendChild(A);r.appendChild(t);C.appendChild(F);p.appendChild(f);p.appendChild(r);
m.appendChild(B);m.appendChild(p);m.appendChild(C);E.appendChild(H);E.appendChild(I);D.appendChild(G);d.appendChild(c);d.appendChild(m);d.appendChild(E);d.appendChild(D);$(a).before(d);notClicked||($(".inputDiv").next().css("display","block"),$("textarea").css("display","block"));contentEditableBr();recreatePage2();makeSortable()}
function recreatePage1(){$("#page1").empty();var a=document.createElement("div"),d=document.createElement("p");d.appendChild(document.createTextNode("Instructors Details"));d.className="bold underline";var c=document.createElement("div");c.contentEditable="true";c.className="inputDiv form-control";c.setAttribute("onkeyup","divToInput(this)");c.setAttribute("onkeydown","divToInput(this)");var b=document.createElement("textarea");b.id="paragraphTextarea";b.setAttribute("onkeyup","inputToDiv(this)");
b.setAttribute("onkeydown","inputToDiv(this)");$(b).css("display","none");var e=$("#page2 > #lessonPlanTemplate > #instructorsDetails").html().trim().replace(/\t/g,"");$(c).html(e);$(c).keydown(function(a){if(8===a.keyCode&&"<p><br></p>"===$(this).html())return!1});$(b).val(e);a.appendChild(d);a.appendChild(c);a.appendChild(b);$("#page1").append(a);$(".lesson").each(function(){var a=document.createElement("div");a.className="mainSection section";var b=document.createElement("div");b.className="lessonTitle";
var d=document.createElement("p");d.appendChild(document.createTextNode("Lesson Title"));var c=document.createElement("div");c.contentEditable="true";c.className="inputDiv contenteditableBr form-control";c.setAttribute("onkeyup","divToInput(this)");c.setAttribute("onkeydown","divToInput(this)");var e=document.createElement("input");e.setAttribute("onkeyup","inputToDiv(this)");e.setAttribute("onkeydown","inputToDiv(this)");e.className="lessonTitleInput form-control";$(c).html($(this).find(".lessonHeader").children().eq(0).html());
$(e).val($(this).find(".lessonHeader").children().eq(0).html());$(e).css("display","none");var f=document.createElement("p");f.appendChild(document.createTextNode("Lesson Subtitle"));var k=document.createElement("div");k.contentEditable="true";k.className="inputDiv contenteditableBr form-control";k.setAttribute("onkeyup","divToInput(this)");k.setAttribute("onkeydown","divToInput(this)");var l=document.createElement("input");l.setAttribute("onkeyup","inputToDiv(this)");l.setAttribute("onkeydown","inputToDiv(this)");
l.className="lessonSubtitleInput form-control";$(k).html($(this).find(".lessonHeader").children().eq(1).html());$(l).val($(this).find(".lessonHeader").children().eq(1).text());$(l).css("display","none");var g=document.createElement("input");g.setAttribute("onchange","setActualValue()");g.setAttribute("type","color");g.className="form-control showAllInput";$(g).css("display","none");var r=$(this).find(".lessonHeader").css("background-color");$(g).val(rgb2hex(r));b.appendChild(d);b.appendChild(c);b.appendChild(e);
b.appendChild(f);b.appendChild(k);b.appendChild(l);b.appendChild(g);a.appendChild(b);$(this).find(".lecPracHeader").each(function(){var b=document.createElement("div");b.className="section contentDivDiv";var c=document.createElement("div");c.className="contentDivDivDraggableDiv progress-bar-striped bg-success";c.style.opacity="0";var d=document.createElement("div");d.className="contentDivDivRight";var e=document.createElement("div");e.className="leftDiv";var h=document.createElement("p");h.appendChild(document.createTextNode("Lesson/ICA Type"));
var f=document.createElement("select");f.setAttribute("onchange","setActualColour(this)");f.className="inputDiv custom-select";var g=document.createElement("option");g.appendChild(document.createTextNode("Lecture"));g.setAttribute("value","Lecture");var k=document.createElement("option");k.appendChild(document.createTextNode("Practical"));k.setAttribute("value","Practical");var l=document.createElement("option");l.appendChild(document.createTextNode("Tutorial"));l.setAttribute("value","Tutorial");
var p=document.createElement("option");p.appendChild(document.createTextNode("Remark"));p.setAttribute("value","Remark");var m=document.createElement("option");m.appendChild(document.createTextNode("E-Learning"));m.setAttribute("value","E-Learning");var n=document.createElement("option");n.appendChild(document.createTextNode("In Course Assessment"));n.setAttribute("value","In Course Assessment");f.appendChild(g);f.appendChild(k);f.appendChild(l);f.appendChild(p);f.appendChild(m);f.appendChild(n);
$(f).val($(this).find(".lecPracDiv :first-child").text());g=document.createElement("input");g.setAttribute("onchange","setActualValue()");g.setAttribute("type","color");g.className="form-control";$(g).css("display","none");k=$(this).find(".lecPracDiv").css("background-color");$(g).val(rgb2hex(k));e.appendChild(h);e.appendChild(f);e.appendChild(g);h=document.createElement("div");h.className="flex rightDiv";f=document.createElement("div");f.className="page1Content";g=document.createElement("p");g.appendChild(document.createTextNode("Title"));
k=document.createElement("div");k.contentEditable="true";k.className="inputDiv contenteditableBr form-control";k.setAttribute("onkeyup","divToInput(this)");k.setAttribute("onkeydown","divToInput(this)");l=document.createElement("input");l.setAttribute("onkeyup","inputToDiv(this)");l.setAttribute("onkeydown","inputToDiv(this))");l.setAttribute("type","text");$(k).html($(this).find(".lessonPlanContent .lessonPlanContentP").html());$(l).val($(this).find(".lessonPlanContent .lessonPlanContentP").html());
$(l).css("display","none");p=document.createElement("p");p.appendChild(document.createTextNode("Topics"));m=document.createElement("div");m.contentEditable="true";m.className="inputDiv form-control";m.setAttribute("onkeyup","divToInput(this)");m.setAttribute("onkeydown","divToInput(this)");n=document.createElement("textarea");n.setAttribute("onkeyup","inputToDiv(this)");n.setAttribute("onkeydown","inputToDiv(this)");$(n).css("display","none");var q=$(this).find(".lessonPlanContent ul")[0].outerHTML.trim().replace(/\t/g,
"");$(m).html(q);$(n).val(q);$(m).keydown(function(a){if(8===a.keyCode&&"<ul><li><br></li></ul>"===$(this).html())return!1});f.appendChild(g);f.appendChild(k);f.appendChild(l);f.appendChild(p);f.appendChild(m);f.appendChild(n);h.appendChild(f);f=document.createElement("button");f.className="closeImg close";f.setAttribute("onclick","removeLessonContent(this)");f.setAttribute("type","button");f.setAttribute("aria-label","Close");g=document.createElement("span");g.setAttribute("aria-hidden","true");
g.innerHTML="&times;";f.appendChild(g);d.appendChild(e);d.appendChild(h);b.appendChild(c);b.appendChild(d);b.appendChild(f);a.appendChild(b)});b=document.createElement("div");b.className="addLessonContent";d=document.createElement("p");d.appendChild(document.createTextNode("Add New Lesson/ICA"));c=document.createElement("i");e=document.createElement("button");e.className="closeImg close";f=document.createElement("span");b.setAttribute("onclick","addLessonContent(this)");c.className="fas fa-plus-circle";
e.setAttribute("onclick","removeLessonContent(this)");e.setAttribute("type","button");e.setAttribute("aria-label","Close");f.setAttribute("aria-hidden","true");f.innerHTML="&times;";e.appendChild(f);b.appendChild(c);b.appendChild(d);a.appendChild(b);a.appendChild(e);$("#page1").append(a)});a=document.createElement("div");d=document.createElement("i");c=document.createElement("p");a.id="addLessonSection";a.className="addLessonContent";a.setAttribute("onclick","addLessonSection(this)");a.style.color=
"white";d.className="fas fa-plus-circle";c.appendChild(document.createTextNode("Add New Lesson"));a.appendChild(d);a.appendChild(c);d=document.createElement("div");d.className="footerSection";c=document.createElement("p");c.appendChild(document.createTextNode("Footnote"));b=document.createElement("div");b.contentEditable="true";b.className="inputDiv contenteditableBr form-control";b.setAttribute("onkeyup","divToInput(this)");b.setAttribute("onkeydown","divToInput(this)");e=document.createElement("input");
e.setAttribute("type","text");e.setAttribute("onkeyup","inputToDiv(this)");e.setAttribute("onkeydown","inputToDiv(this)");e.id="lessonPlanFooter";$(b).html($("#lessonPlanTemplate .sub").html());$(e).val($("#lessonPlanTemplate .sub").html());$(e).css("display","none");d.appendChild(c);d.appendChild(b);d.appendChild(e);c=document.createElement("br");b=document.createElement("div");b.style.display="flex";b.style.flexDirection="column";e=document.createElement("button");e.appendChild(document.createTextNode("Generate HTML for BlackBoard"));
e.setAttribute("onclick","generateHTML()");e.className="btn btn-primary";var k=document.createElement("button");k.appendChild(document.createTextNode("Save As HTML (For Reimport)"));k.setAttribute("onclick","saveHTMLFile()");k.className="btn btn-secondary";var l=document.createElement("button");l.appendChild(document.createTextNode("Show All Hidden HTML"));l.setAttribute("onclick","showAllInput(this)");l.className="btn btn-secondary";b.appendChild(e);b.appendChild(k);b.appendChild(l);e=document.getElementById("page1");
e.appendChild(a);e.appendChild(d);e.appendChild(c);e.appendChild(b);contentEditableBr();makeSortable()}
function recreatePage2(){$("#page2").empty();var a=document.createElement("div");a.id="lessonPlanTemplate";var d=document.createElement("p");d.appendChild(document.createTextNode("Instructors Details"));var c=document.createElement("div"),b=$("#paragraphTextarea").val();$(c).html(b);d.className="bold underline";c.id="instructorsDetails";a.append(d);a.append(c);$(".mainSection").each(function(){var b=document.createElement("div"),c=document.createElement("div");c.style.backgroundColor=$(this).find(".lessonTitle > :last-child").val();
var d=document.createElement("p");$(d).html($(this).find(".lessonTitleInput").val());var h=document.createElement("p");$(h).html($(this).find(".lessonSubtitleInput").val());b.className="lesson";c.className="lessonHeader";d.className="bold";h.className="em";c.appendChild(d);c.appendChild(h);b.appendChild(c);$(this).find(".contentDivDiv").each(function(){var a=document.createElement("div"),c=document.createElement("div"),d=document.createElement("p");$(c).css("background-color",$(this).find(".leftDiv input:nth-child(3)").val());
$(d).html($(this).find(".leftDiv :nth-child(2)").val());c.appendChild(d);var e=document.createElement("div"),f=document.createElement("p");$(f).html($(this).find(".rightDiv .page1Content :nth-child(2)").html());var h=$(this).find(".rightDiv .page1Content :nth-child(5)").html();$(e).html(h);a.className="lecPracHeader";c.className="lecPracDiv";d.className="bold";e.className="lessonPlanContent";f.className="lessonPlanContentP";$(e).prepend(f);a.appendChild(c);a.appendChild(e);b.appendChild(a)});a.append(b)});
d=document.createElement("p");$(d).html($("#lessonPlanFooter").val());d.className="sub";a.append(d);$("#page2").append(a)}function setInputValue(){recreatePage1()}function setActualValue(){recreatePage2()}function setActualColour(a){var d=a.value,c=JSON.parse(colourTemplate);c[d]&&$(a).next().val(c[d]);recreatePage2()}function generateHTML(){$("#popupDiv").modal("show");$("#popup .modal-body textarea").val($("#page2").html().trim())}
function closePopup(){$("#popupDiv").modal("hide");$("#popup .generateHTMLRedText").css("display","none")}function copyToClipboard(){$("#popup .modal-body textarea")[0].select();document.execCommand("copy");$("#popup .generateHTMLRedText").css("display","block")}function copyCommand(){var a=document.createElement("textarea");$(a).text(selectedText);$("#masterDiv").append(a);$(a)[0].select();document.execCommand("copy");$(a).remove()}
function checkOverlapLink(a){a=htmlEncode(a);var d=focusedInput;startIndex=d.next().val().indexOf(a);var c=escape("<a href="),b=escape("</a>");if((new RegExp("("+c+").*("+escape(a)+").*("+b+")")).test(escape(d.next().val())))return alert("Error! You already made this a link."),!1;if(-1!==startIndex)return!0;alert("Error! Make sure the text selected is not overlapping with another link.");return!1}
function promptLink(){0<selectedText.length&&checkOverlapLink(selectedText)&&($("#linkInput").val("https://"),$("#linkBoxOptions").text("Webpage"),$("#linkBoxDiv").modal("show"))}function hideLinkBox(){$("#linkBoxDiv").modal("hide");changeInputBoxSelection(1)}function hideExcelBox(){$("#excelSelectInput").removeClass("is-invalid");$("#excelSelectInput").removeClass("is-valid");$("#inputGroupFile01").val(null);$("#uploadedFileName").html("Choose file");$("#excelBoxDiv").modal("hide")}
function changeInputBoxSelection(a){$(".dropdown-menu > .active.dropdown-item")[0].classList.remove("active");var d=$("#linkBoxOptions"),c=$("#linkInput");switch(a){case 1:d.text("Webpage");c[0].setAttribute("placeholder","https://");c.val("https://");$(".dropdown-menu > a:first-child")[0].classList.add("active");break;case 2:d.text("Email");c[0].setAttribute("placeholder","example@nyp.edu.sg");c.val("");/^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/.test(selectedText)&&
c.val(htmlEncode(selectedText));$(".dropdown-menu > a:nth-child(2)")[0].classList.add("active");break;case 3:d.text("Javascript"),c[0].setAttribute("placeholder","alert('Hello')"),c.val(""),$(".dropdown-menu > a:nth-child(4)")[0].classList.add("active")}}
function checkAndDisplayAlert(){if($("#linkInput").val()){var a=document.createElement("div");a.className="alert alert-warning fade show";a.id="linkBoxAlertError";a.setAttribute("role","alert");var d=document.createElement("p"),c=document.createElement("div"),b=document.createElement("button");b.className="close";b.setAttribute("type","button");b.setAttribute("data-dismiss","alert");b.setAttribute("aria-label","Close");var e=document.createElement("span");b.setAttribute("aria-hidden","true");b.innerHTML=
"&times;";b.appendChild(e);c.appendChild(b);a.appendChild(d);a.appendChild(c);c=$("#linkInput").val();b=$("#linkBoxOptions").text();"Webpage"===b?/https?:\/\/(www\.)?[-a-zA-Z0-9@:%._\+~#=]{2,256}\.[a-z]{2,6}\b([-a-zA-Z0-9@:%_\+.~#?&//=]*)/.test(c)?closeAlert():(closeAlert(),d.appendChild(document.createTextNode("The URL entered does not match the format.")),$("#linkBox > .modal-content > .modal-body").prepend(a)):"Email"===b&&(/^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/.test(c)?
closeAlert():(closeAlert(),d.appendChild(document.createTextNode("The email entered does not match the format.")),$("#linkBox > .modal-content > .modal-body").prepend(a)))}}function whichLinkSelection(){var a=$("#linkBoxOptions").text();if("Webpage"===a)return"";if("Email"===a)return"mailto:";if("Javascript"===a)return"javascript:";alert("Unexpected error");return null}
function convertToLink(){closeAlert();var a=document.createElement("div");a.className="alert alert-danger fade show";a.id="linkBoxAlertError";a.setAttribute("role","alert");var d=document.createElement("p"),c=document.createElement("div"),b=document.createElement("button");b.className="close";b.setAttribute("type","button");b.setAttribute("data-dismiss","alert");b.setAttribute("aria-label","Close");var e=document.createElement("span");b.setAttribute("aria-hidden","true");b.innerHTML="&times;";b.appendChild(e);
c.appendChild(b);a.appendChild(d);a.appendChild(c);if(c=$("#linkInput").val()){if(""===whichLinkSelection()){if(!/https?:\/\/(www\.)?[-a-zA-Z0-9@:%._\+~#=]{2,256}\.[a-z]{2,6}\b([-a-zA-Z0-9@:%_\+.~#?&//=]*)/.test(c)&&!confirm("The URL entered does not match the format. Do you want to continue?"))return d.appendChild(document.createTextNode("The URL entered does not match the format.")),a.className="alert alert-warning fade show",$("#linkBox > .modal-content > .modal-body").prepend(a),!1}else if("mailto:"===
whichLinkSelection()&&!/^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/.test(selectedText)&&!confirm("The email entered does not match the format. Do you want to continue?"))return d.appendChild(document.createTextNode("The email entered does not match the format.")),a.className="alert alert-warning fade show",$("#linkBox > .modal-content > .modal-body").prepend(a),!1;b=htmlEncode(selectedText);
var k=focusedInput;e=k.html();c=whichLinkSelection()?"<a href='"+whichLinkSelection()+$("#linkInput").val()+"' target='_blank'>"+b+"</a>":"<a href='"+$("#linkInput").val()+"' target='_blank'>"+b+"</a>";startIndex=k.next().val().indexOf(b);var l=escape("<a href="),h=escape("</a>");(new RegExp("("+l+").*("+escape(b)+").*("+h+")")).test(escape(k.next().val()))?(d.appendChild(document.createTextNode("Error! You already made this a link.")),$("#linkBox > .modal-content > .modal-body").prepend(a)):-1!==
startIndex?(a=e.substring(0,startIndex),d=e.substring(startIndex+b.length),a=a+c+d,focusedInput.next().val(a),focusedInput.html(focusedInput.next().val()),setActualValue()):(d.appendChild(document.createTextNode("Error! Make sure the text selected is not overlapping with another link.")),$("#linkBox > .modal-content > .modal-body").prepend(a));hideLinkBox()}else d.appendChild(document.createTextNode("Please enter a link.")),$("#linkBox > .modal-content > .modal-body").prepend(a)}
function divToInput(a){$(a).next().val(a.innerHTML);setActualValue()}function inputToDiv(a){$(a).prev().html(a.value);setActualValue()}
function saveHTMLFile(){try{new Blob;var a=prompt("Please enter filename:","BlackBoard Lesson Plan");if(a){var d=document.getElementById("lessonPlanTemplate").outerHTML.toString(),c=new Blob([d],{type:"text/html;charset=utf-8"});saveAs(c,a+".html")}}catch(e){a=document.createElement("div");a.style.position="fixed";a.style.top="0";a.style.left="0";a.style.width="100%";a.style.height="100%";a.style.backgroundColor="rgba(25,25,25,0.6)";a.id="saveFileAlertBackground";d=document.createElement("div");d.className=
"alert alert-danger alert-dismissible fade show";d.setAttribute("role","alert");d.style.position="absolute";d.style.top="40%";d.style.left="20%";d.style.width="60%";d.style.height="20%";c=document.createElement("p");c.innerHTML="<strong>File saving not supported</strong><br>To save the file, press <kbd><kbd>ctrl</kbd> + <kbd>s</kbd></kbd>";var b=document.createElement("button");b.setAttribute("data-dismiss","alert");b.setAttribute("aria-label","close");b.appendChild(document.createTextNode("Close"));
b.className="btn btn-primary";b.onclick=function(){$("#saveFileAlertBackground").remove()};d.appendChild(c);d.appendChild(b);a.appendChild(d);$("#masterDiv").append(a);console.log("Error message: "+e)}}
function showAllInput(a){notClicked?($(".inputDiv").next().css("display","block"),$("textarea:not(#popup textarea)").css("display","block"),$(".showAllInput").css("display","block"),a.innerHTML="Hide All Hidden HTML",notClicked=!1):($(".inputDiv").next().css("display","none"),$("textarea:not(#popup textarea)").css("display","none"),$(".showAllInput").css("display","none"),a.innerHTML="Show All Hidden HTML",notClicked=!0)}
function checkEnterKey(a){if(13===a.keyCode)return document.execCommand("insertHTML",!1,"<br /><br />"),!1}function contentEditableBr(){$(document).off("keydown",".contenteditableBr",checkEnterKey);$(document).on("keydown",".contenteditableBr",checkEnterKey)}function selectAll(a){a.setSelectionRange(0,a.value.length)}var hexDigits="0123456789abcdef".split("");function rgb2hex(a){return(a=a.match(/^rgb\((\d+),\s*(\d+),\s*(\d+)\)$/))?"#"+hex(a[1])+hex(a[2])+hex(a[3]):"#000000"}
function hex(a){return isNaN(a)?"00":hexDigits[(a-a%16)/16]+hexDigits[a%16]}function htmlEncode(a){return $("<div/>").text(a).html()}function htmlDecode(a){return a.replace(/&#(\d+);?/g,function(a,c){return String.fromCharCode(c)})};
